---
title: "DES_Data"
format: html
editor: visual
---gitcreds::gitcreds_set()
---

#### Libraries

```{r}
library(tidyverse)
library(simmer)
library(simmer.plot)
```

#### Loading Data 

```{r}
interarrival <- read.csv("1_data/01_interarrival_by_timeblock_hourly_cy2025.csv")
case_mix <- read.csv("1_data/02_case_mix_by_timeblock_cy2025.csv")
first_seen <- read.csv("1_data/03_arrival_to_first_seen_distribution_by_triage_cy2025.csv")
workup <- read.csv("1_data/05_generic_workup_duration_distribution_by_complexity_cy2025.csv")
imaging_prob <- read.csv("1_data/07_imaging_probability_and_modality_mix_by_complexity_acuity_cy2025.csv")
imaging_time <- read.csv("1_data/08_imaging_duration_distribution_by_modality_cy2025.csv")
```

```{r}
mean_interarrival <- interarrival$mean_interarrival_min[1]


#instead of always [1], sample values
sample_first_seen <- function() {
  sample(first_seen$median_min, 1)  # median wait time
}

sample_workup <- function() {
  sample(workup$median_min, 1)  # median workup time
}

sample_imaging <- function() {
  sample(imaging_time$total_imaging_median_min, 1)  # median imaging time
}

ed_path <- trajectory("ED patient") %>%
  timeout(function() sample_first_seen()) %>%
  timeout(function() sample_workup()) %>%
  timeout(function() sample_imaging())

env <- simmer("ED")

env %>%
  add_generator("patient", ed_path, function() rexp(1, rate = 1 / mean_interarrival))

env %>% run(until = 5000)

arrivals <- get_mon_arrivals(env)
arrivals
nrow(arrivals)
table(arrivals$finished)
```

```{r}
ggplot(arrivals, aes(x = activity_time)) +
  geom_histogram(bins = 25) +
  labs(
    title = "Simulated Length of Stay (LOS)",
    x = "Minutes in System",
    y = "Number of Patients"
  )
```

```{r}
ggplot(arrivals, aes(x = activity_time)) +
  geom_density(fill = "blue", alpha = 0.4) +
  labs(
    title = "Density of Simulated LOS",
    x = "Minutes",
    y = "Density"
  )
```

```{r}
ggplot(arrivals, aes(x = start_time, y = end_time)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Patient Flow Through System",
    x = "Arrival Time",
    y = "Departure Time"
  )
```

```{r}
ggplot(arrivals, aes(x = start_time, y = activity_time)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "LOS vs Arrival Time",
    x = "Arrival Time",
    y = "LOS (Minutes)"
  )
```

```{r}
ggplot(arrivals, aes(x = finished)) +
  geom_bar() +
  labs(
    title = "Completed vs Incomplete Patients",
    x = "Finished",
    y = "Count"
  )
```
